### ISSUE TITLE
Feature Request: Add support for MinGW

### ISSUE THREAD

**Issue by mubix** [meme/hellscape#8]
It would be nice to be able to use this plugin in MinGW

**Comment by meme** [comment]
Not familiar with the process of using GCC plugins on MinGW, have you tried using it as-is?

**Comment by mubix** [comment]
I tried this:
```
i686-w64-mingw32-gcc-win32 -Wall -Os -fPIC -fplugin=/root/hellscape/build/hellscape.so -fplugin-arg-hellscape-sub nanomet.c -o hell.exe -s -lws2_32 -lwininet
```
And got this:
```
# i686-w64-mingw32-gcc-win32 -Wall -Os -fPIC -fplugin=/root/hellscape/build/hellscape.so -fplugin-arg-hellscape-sub nanomet.c -o hell.exe -s -lws2_32 -lwininet
error: expected GCC 9.3
cc1: error: fail to initialize plugin /root/hellscape/build/hellscape.so
```

**Comment by meme** [comment]
The GCC plug-in headers you are compiling against are not the same as the ones you are running against, you'd need to modify the `CMakeLists.txt` to change the includes directory to the plug-in headers of `i686-w64-mingw32-gcc-win32`

**Comment by meme** [comment]
(I assume this has been resolved.)
